### ISSUE TITLE
Contribute file for explaining how to work with me 

### ISSUE THREAD

**Issue by artemtsai** [artemtsai/my-recipes#2]
## TODO
- [x] 'CONTRIBUTING.md' created
- [x] Explain Fork and Pull request Model
- [x] Link to it from 'README.md'
